apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: myapp
spec:
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: myapp:latest
  resources:
    - name: source
      type: git
  tasks:
    - name: posts-service
      taskRef:
        name: build-docker
      params:
        - name: BUILDER_IMAGE
          value: posts-service
      resources:
        inputs:
          - name: source
            resource: source
    - name: editor-service
      taskRef:
        name: build-docker
      params:
        - name: BUILDER_IMAGE
          value: editor-service
      resources:
        inputs:
          - name: source
            resource: source